services:
  wire-pod:
    hostname: escapepod
    image: ghcr.io/baronhoot/wire-pod:main
    restart: unless-stopped
    runtime: nvidia
    environment:
      - WHISPER_MODEL=base
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - 443:443
      - 8080:8080
      - 80:80
      - 8084:8084
    volumes:
      - wire-pod-data:/chipper/
      - wire-pod-whisper:/whisper.cpp/
volumes:
  wire-pod-data:
    driver: local
  wire-pod-whisper:
    driver: local
